ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
C     System.Inc                                            c
C                                                           c
C     Information About The System; Various Constants       c
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      Integer          Ntemp,Nstep
      
      Double Precision Twopi,Xold(9),Uold(9),Ptemp,Beta(9)

      Common /sstmmw/  Twopi,Xold,Uold,Ptemp,Beta,Ntemp,Nstep
