#! /bin/csh -f

foreach q  (10.)
  echo " --- q ${q} "  	
  echo " --- q ${q} "  	>> out
  cat > fort.15  <<endofdata
  ibeg  , delt  tmax  tequil nsamp 
   1     0.001  .1   .00    2 
npart tempinit rho      rcp  iseed
256  1.0   0.75   2.5  123456
 q temp
 ${q}  1.
iout gr  iout2  ivacf  t0vacf t0stress iout3
33   5000   34     2      50       10        35
endofdata
 cp lj.res          fort.11
 time  ../Source/MD   >> out
 cp fort.21         lj.res
 mv fort.66         lj.prt
 mv fort.34         lj.vacf.${q}
 mv fort.36         lj.dTemp
 mv fort.37         lj.dVel
 mv fort.39         lj.dVel2

 #perform block analysis
  cp lj.prth fort.31
  mv  lj.prt fort.32
 ../Block/block   >>  out 
 rm fort.*
end
exit
